/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authenticatedImport } from './routes/__authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as authenticatedProfileIndexImport } from './routes/__authenticated/profile/index'
import { Route as authenticatedExpensesIndexImport } from './routes/__authenticated/expenses/index'
import { Route as authenticatedCreateExpenseIndexImport } from './routes/__authenticated/create-expense/index'

// Create/Update Routes

const authenticatedRoute = authenticatedImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedProfileIndexRoute = authenticatedProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedExpensesIndexRoute = authenticatedExpensesIndexImport.update(
  {
    path: '/expenses/',
    getParentRoute: () => authenticatedRoute,
  } as any,
)

const authenticatedCreateExpenseIndexRoute =
  authenticatedCreateExpenseIndexImport.update({
    path: '/create-expense/',
    getParentRoute: () => authenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/__authenticated/create-expense/': {
      id: '/__authenticated/create-expense/'
      path: '/create-expense'
      fullPath: '/create-expense'
      preLoaderRoute: typeof authenticatedCreateExpenseIndexImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/expenses/': {
      id: '/__authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof authenticatedExpensesIndexImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/profile/': {
      id: '/__authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedProfileIndexImport
      parentRoute: typeof authenticatedImport
    }
  }
}

// Create and export the route tree

interface authenticatedRouteChildren {
  authenticatedCreateExpenseIndexRoute: typeof authenticatedCreateExpenseIndexRoute
  authenticatedExpensesIndexRoute: typeof authenticatedExpensesIndexRoute
  authenticatedProfileIndexRoute: typeof authenticatedProfileIndexRoute
}

const authenticatedRouteChildren: authenticatedRouteChildren = {
  authenticatedCreateExpenseIndexRoute: authenticatedCreateExpenseIndexRoute,
  authenticatedExpensesIndexRoute: authenticatedExpensesIndexRoute,
  authenticatedProfileIndexRoute: authenticatedProfileIndexRoute,
}

const authenticatedRouteWithChildren = authenticatedRoute._addFileChildren(
  authenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof authenticatedRouteWithChildren
  '/about': typeof AboutIndexRoute
  '/home': typeof HomeIndexRoute
  '/create-expense': typeof authenticatedCreateExpenseIndexRoute
  '/expenses': typeof authenticatedExpensesIndexRoute
  '/profile': typeof authenticatedProfileIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof authenticatedRouteWithChildren
  '/about': typeof AboutIndexRoute
  '/home': typeof HomeIndexRoute
  '/create-expense': typeof authenticatedCreateExpenseIndexRoute
  '/expenses': typeof authenticatedExpensesIndexRoute
  '/profile': typeof authenticatedProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__authenticated': typeof authenticatedRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/home/': typeof HomeIndexRoute
  '/__authenticated/create-expense/': typeof authenticatedCreateExpenseIndexRoute
  '/__authenticated/expenses/': typeof authenticatedExpensesIndexRoute
  '/__authenticated/profile/': typeof authenticatedProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/home'
    | '/create-expense'
    | '/expenses'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/home'
    | '/create-expense'
    | '/expenses'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/__authenticated'
    | '/about/'
    | '/home/'
    | '/__authenticated/create-expense/'
    | '/__authenticated/expenses/'
    | '/__authenticated/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRoute: typeof authenticatedRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRoute: authenticatedRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__authenticated",
        "/about/",
        "/home/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__authenticated": {
      "filePath": "__authenticated.tsx",
      "children": [
        "/__authenticated/create-expense/",
        "/__authenticated/expenses/",
        "/__authenticated/profile/"
      ]
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/__authenticated/create-expense/": {
      "filePath": "__authenticated/create-expense/index.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/expenses/": {
      "filePath": "__authenticated/expenses/index.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/profile/": {
      "filePath": "__authenticated/profile/index.tsx",
      "parent": "/__authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
